### PR TITLE
wip: Fix travis

### PR DESCRIPTION
**Pull request by andrewsmedina**
* fix yaml indentation
* simplifying django settings

### CODE REVIEW

**Comment by auvipy** [comment]
still travis failing

**Comment by andrewsmedina** [comment]
@auvipy I know, I'm working on it :)

**Comment by galuszkak** [comment]
This is somehow going in cross fire. @auvipy in https://github.com/jazzband/django-admin2/pull/444/files (which he self accepted) upgraded the versions of libraries.

Now in this PR @andrewsmedina is downgrading them back to where they were. 

This actually leads me to believe that maybe we should design idea what we want to achieve, and then execute it rather than going back and forth, because it will 
* save a time to everyone
* wont create confusion to others

**Comment by andrewsmedina** [comment]
@galuszkak it is not a cross fire. The tests are broken since we moved to jazzband. I just downgrade the deps to figure out if the travis output will change. But it is not the problem.

Currently we have 3 commiters, me, you and @auvipy. I believe that a good way is to open pull requests and ask to the anothers commiters to do the merge.

What do you guys think about it?

**Comment by auvipy** [comment]
+1

**Comment by andrewsmedina** [comment]
I figure out what is happening, I created another PR with the fixes: https://github.com/jazzband/django-admin2/pull/448

**Pull request closed without merging**
