### PR TITLE
update minor versions

### PR DESCRIPTION
**Pull request by auvipy**
and check what fails to fix them incrementally for 0.7.1 release

### CODE REVIEW

**Comment by auvipy** [comment]
merging to dev and later fix the test failures one by one

**Comment by andrewsmedina** [comment]
I'm -1 for this merge. We should fix the tests before the merge. The tests are broken because the code are broken too.

**Comment by auvipy** [comment]
this is on development branch and the fails are on dev branch. Intended to fix the failures in dev branch so no problem in merging as it wont effect the released ones.

**Comment by andrewsmedina** [comment]
@auvipy we should not merge failing PR's in the development branch.

**Pull request merged**
